#facebook:
#  client:
#    clientId: <your-client-id>
#    clientSecret: <your-secret>
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me
google :
  client :
    clientId : 922211077475-3cq2cb950gith2arb2mg54cjs9o99n89.apps.googleusercontent.com
    clientSecret: 4xXQyncq8TdZVplifkJ9FVpB
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    accesskey: AKIAIBSRI52NR7WSOLBQ
    secretkey: 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